# Change these first
owner: ShadowEmperorYT # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Beast Bot Site
    url: https://beast-bot.ga
  - name: Beast Bot
    url: https://beast-bot-discord.herokuapp.com/
 
status-website:
  favicon: https://beast-bot.ga/img/kisspng-portable-network-graphics-computer-icons-transpare-braingoodgames-5c9d9c5093e378.8617067815538330406058.png
  theme: dark
  cname: status.beast-bot.ga
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #baseUrl: /Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Beast bot status
  introTitle: "**Beast Bot** is a fun and moderation bot for your discord server with many commands."
  introMessage: make your server a safe and fun server for evreybody. 
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://beast-bot.ga/

i18n:
  footer: CaptainBeast#1394 - all rights reserved
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
